### PR TITLE
adding a couple screenshots to README.md

### PR DESCRIPTION
**Pull request by felipesanches**
When you merge this, please change the raw image URL to point to the master branch of the trufont/trufont repository.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Relative URLs work just fine here, see fo example https://github.com/khaledhosny/reem-kufi/blob/master/README.md.

**Comment by felipesanches** [comment]
thanks, @khaledhosny

**Comment by felipesanches** [comment]
Do you want me to create new, updated screenshots with the latest development version of TruFont ?

**Comment by davelab6** [comment]
@adrientetar I suggest this can be closed as https://github.com/trufont/trufont now has a screenshot.

**Pull request closed without merging**
