### PR TITLE
requirements.txt: use -e (editable) mode for packages cloned from git repository

### LINKED ISSUE #158: Build from source error
I got this,
```
Pathums-MacBook-Pro:trufont Pathum$ sudo pip install -r requirements.txt
The directory '/Users/Pathum/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Pathum/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting booleanOperations from git+https://github.com/typemytype/booleanOperations.git#egg=booleanOperations (from -r requirements.txt (line 1))
  Cloning https://github.com/typemytype/booleanOperations.git to /private/tmp/pip-build-_V3zR9/booleanOperations
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-_V3zR9/booleanOperations/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-_V3zR9/booleanOperations
```

And `sudo -H` got this
```
Pathums-MacBook-Pro:trufont Pathum$ sudo -H pip install -r requirements.txt
Collecting booleanOperations from git+https://github.com/typemytype/booleanOperations.git#egg=booleanOperations (from -r requirements.txt (line 1))
  Cloning https://github.com/typemytype/booleanOperations.git to /private/tmp/pip-build-uZeywy/booleanOperations
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-uZeywy/booleanOperations/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-uZeywy/booleanOperations
Pathums-MacBook-Pro:trufont Pathum$ 
```

### PR DESCRIPTION
**Pull request by anthrotype**
Closes #158.

### CODE REVIEW

**Comment by adrientetar** [comment]
Thanks. Do we still need to specify cython now that booleanOperations installs it by itself?

Btw if you remove it, it's also in the present .travis.yml.

**Comment by anthrotype** [comment]
good point. no, we don't. I'll remove it.

**Comment by davelab6** [comment]
Nice!

**Comment by anthrotype** [comment]
ack!.. Travis failed with `Setuptools >= 18.0 is required`.
so we also need to `pip install --upgrade setuptools`. I'll do that.

**Comment by adrientetar** [comment]
Apparently build fails because the bot doesn't have recent-enough setuptools for booleanOps.

**Comment by anthrotype** [comment]
I thought I could specify `setuptools>=18.0` as part of `requirements.txt` but apparently it wants to be upgraded before the rest of `requirements.txt`...  :-1:
please wait before you merge, as I may squash it.

**Comment by anthrotype** [comment]
ok, now i'm happy if you're happy.

**Comment by adrientetar** [comment]
Yes, thanks.

**Comment by anthrotype** [comment]
cool

**Pull request merged**
