### PR TITLE
Shapes tool

### LINKED ISSUE #504: Tools for quickly creating simple geometric shapes
For example, it's hard to draw a perfect circle only with pen tools.

Showing anchors' coordinates is also a good workaround.

### PR DESCRIPTION
**Pull request by eliheuer**
Fixes #504.

### CODE REVIEW

**Comment by moyogo** [comment]
Cool!

Travis fails the flake8 test because of a few unused imports:
```bash
$ flake8 --config=setup.cfg Lib/trufont`
Lib/trufont/drawingTools/shapesTool.py:1:1: F401 'PyQt5.QtCore.QPointF' imported but unused
Lib/trufont/drawingTools/shapesTool.py:2:1: F401 'PyQt5.QtGui.QColor' imported but unused
Lib/trufont/drawingTools/shapesTool.py:5:1: F401 'defcon.Glyph' imported but unused
Lib/trufont/drawingTools/shapesTool.py:7:1: F401 'trufont.tools.bezierMath' imported but unused
```

**Comment by eliheuer** [comment]
Fixed, thanks @moyogo!

**Comment by moyogo** [comment]
The circle tool produces round diamonds.

It looks better if you use the same ratio as https://github.com/typemytype/shapeToolRoboFontExtension/blob/master/ShapeTool.roboFontExt/lib/drawShapesTool.py:
```diff
diff --git a/Lib/trufont/drawingTools/shapesTool.py b/Lib/trufont/drawingTools/shapesTool.py
index 1f20755..aac9669 100644
--- a/Lib/trufont/drawingTools/shapesTool.py
+++ b/Lib/trufont/drawingTools/shapesTool.py
@@ -69,10 +69,12 @@ class ShapesTool(BaseTool):
         if event.button() == Qt.RightButton:
             midX = (startX + endX) / 2
             midY = (startY + endY) / 2
-            handleXStart = (midX + startX) / 2
-            handleXEnd = (midX + endX) / 2
-            handleYStart = (midY + startY) / 2
-            handleYEnd = (midY + endY) / 2
+            halfWidthX = (endX - startX) / 2
+            halfWidthY = (endY - startY) / 2
+            handleXStart = midX - halfWidthX * .55
+            handleXEnd = midX + halfWidthX * .55
+            handleYStart = midY - halfWidthY * .55
+            handleYEnd = midY + halfWidthY * .55

             contour.addPoint((midX, startY), segmentType="curve", smooth=True)
             contour.addPoint((handleXEnd, startY))
```

Compare yours on the left with this one on the right:
capture d ecran 2017-12-30 a 07 18 16

**Comment by eliheuer** [comment]
Thanks again @moyogo! I pushed an update fixing this.

The new update also has a shift key constraint for drawing squares and circles:

trufont504_01

**Pull request merged**
