### PR TITLE
temporarily remove "smart"-sort from UI as it is not implemented yet.

### PR DESCRIPTION
**Pull request by felipesanches**
This is related to issue #28

### CODE REVIEW

**Comment by adrientetar** [comment]
It *is* implemented and it works for me. It's the default sort order &ndash; have you applied another sorting order before doing smart sort again?

**Comment by felipesanches** [comment]
All I see is self.smartSortBox being instantiated and set, but it's status does not seem to be used anywhere...

Am I missing something?

Here's what I see:

```
felipe@guarana:~/devel/github_felipesanches/trufont/Lib$ ack-grep smart -C 1
defconQt/fontView.py
469-
470:        self.smartSortBox = QRadioButton("Smart sort", self)
471-        self.glyphSetBox = QRadioButton("Glyph set", self)
--
491-        elif desc[0]["type"] == "cannedDesign":
492:            self.smartSortBox.setChecked(True)
493-        else:
--
535-        layout = QVBoxLayout(self)
536:        layout.addWidget(self.smartSortBox)
537-        layout.addWidget(self.glyphSetBox)
```

**Comment by adrientetar** [comment]
Lines 601&ndash;602:

```
    else:
        ret = cannedDesign
```

**Comment by felipesanches** [comment]
hmm... That was not trivial or evident. Handling the checkbox this way is a bit misleading I think.

**Comment by adrientetar** [comment]
I always make the last else if and else for exhaustive pattern-matching.

**Comment by felipesanches** [comment]
What I mean is that the checkbox state is set by the user, but it is not read by the program. Instead, it's state is infeered by the state of all other checkboxes, which seems bad code style. I'd suggest you actually check the checkbox value in order to decide whether or not the feature will be enabled.

**Comment by adrientetar** [comment]
The checkboxes are mutually-exclusive and there is a default check, so this checkbox being checked is logically equivalent to others being unchecked.

**Pull request closed without merging**
