### PR TITLE
Rewrite most things

### LINKED ISSUE #254: [bezierMath] lineDistance raises "TypeError: 'NoneType' object is not iterable"
`bezierMath.lineProjection` returns None if the point cannot be projected on the segment. However `bezierMath.lineDistance` that calls `lineProjection` does not check if the returned value is None, and therefore makes Python crash with `TypeError: 'NoneType' object is not iterable`.

Calling `lineProjection` with  `ditchOutOfSegment=False` prevents it to return None and fixes the issue.
`ditchOutOfSegment` argument is True by default.

### PR DESCRIPTION
**Pull request by adrientetar**
cc #240.
Closes #254.

### CODE REVIEW

**Comment by davelab6** [comment]
AWESOME

**Comment by davelab6** [comment]
"1 check failed"?

**Comment by moyogo** [comment]
@davelab6 no worries, we’ll clean that up

**Comment by adrientetar** [comment]
@moyogo Thanks Denis !!

**Comment by davelab6** [comment]
:D

**Pull request merged**
