### PR TITLE
Font Info: Align labels right

### PR DESCRIPTION
**Pull request by madig**
A first sweep. Still needs a more pleasant resizing behavior.

Other dialogs will follow.

### CODE REVIEW

**Comment by adrientetar** [comment]
Maybe we could subclass QLabel into RLabel class no there's no need to repeat?

**Comment by madig** [comment]
Hm, might be a good idea. Will check the source in the coming days if it could be useful elsewhere.

**Comment by davelab6** [comment]
I am contracted by Google to manage the collection.

I just wrote and published
https://github.com/googlefonts/fontbakery/pull/661/files so you can see
where I hope to go this year which will help Debian and similar folks,
since at the moment a lot of the families aren't developed like regular
(libre) software and probably can't belong in main just yet.

**Comment by madig** [comment]
@davelab6 Wrong window?

**Comment by davelab6** [comment]
lol woops. deleting :)

**Pull request merged**
