### PR TITLE
Add Show Coordinates submenu

### PR DESCRIPTION
**Pull request by exer2k**
Added functionality providing the drawing of point and Bézier handle coordinates.

The options are available from View menu, from a separate submenu, for more granular control.

### CODE REVIEW

**Comment by madig** [comment]
Thanks for sending that in, will take a look over the weekend. Please format the code with black in the meantime :)

**Comment by exer2k** [comment]
Whoops! I wasn't aware there are formatting rules applied to the code. Will fix that in a minute.

**Comment by madig** [comment]
I use https://github.com/pre-commit/pre-commit to run checks before committing.

**Comment by exer2k** [comment]
This is a discussion for another issue, but should we add the formatting and/or pre-commit check instructions to `README`?

**Comment by madig** [comment]
Yes :) Can look into it later.

**Comment by madig** [comment]
(Small note on the .gitignore file: you can define git ignore patterns on your local machine by modifying `.config/git/ignore` (maybe you need to set the `core.excludesfile` parameter), so you don't have to touch the `.gitignore` file in random projects you contribute to.)

**Comment by madig** [comment]
Hm, with a fresh configuration, all the options are toggled in the view menu but not necessarily active. I think you want them off by default?

**Comment by exer2k** [comment]
You're right, I'll take a look at it.

**Comment by madig** [comment]
Ok, looks good to me. Thanks! :)

**Pull request merged**
