### PR TITLE
fix bit values for OS2CodePageRanges

### PR DESCRIPTION
**Pull request by felipesanches**
(issue #577)

### CODE REVIEW

**Comment by felipesanches** [comment]
@madig, could you please review & merge this?

**Comment by madig** [comment]
If you make a UFO before this change, select from Vietnamese to Macintosh Character Set and save, apply the change and open the UFO again, Thai to Johab exclusively are checked. Checking Johab and saving does not change the bits saved to the UFO. So there's something else that needs to be fixed.

**Comment by felipesanches** [comment]
thanks, I'll take a look

**Comment by felipesanches** [comment]
it may be yet another off-by-1 bug

**Comment by madig** [comment]
I'm looking at how to add a test for this... custom fields are a pain. So is the structure of the info window...

**Comment by adrientetar** [comment]
You only changed the loading code, not the saving one. Same code in the same file, should probably be factored into a function.

**Comment by madig** [comment]
Just stumbled over that. Made a test, works now. The entire info window could do with a massive refactor... ideally with the GUI construction done in a .ui file and code just for wiring it up...

Now to push it to this branch.

**Comment by madig** [comment]
Done. Thanks again Felipe!

**Pull request merged**
