### PR TITLE
fix git repo URLs for dependencies on README and requirements.txt

### PR DESCRIPTION
**Pull request by felipesanches**
There are broken repo URLs on README & requirements.txt so I tried to fix them. Please let me know if that's good.

### CODE REVIEW

**Comment by madig** [comment]
Uh. Are you working form the right branch?

**Comment by felipesanches** [comment]
well... I think I have an old copy here, sorry

**Comment by felipesanches** [comment]
Oh, wow! I was using a checkout from 2016! :-P

Sorry about the noise!
Captura de Tela 2020-01-30 às 09 47 14

**Comment by madig** [comment]
A blast from the past.

**Comment by felipesanches** [comment]
my mistake was:

* opened trufont/trufont
* clicked "fork"
* github told me I already had a fork
* I clicked on my fork, grabed the URL and checked out that one.
* I read my own outdated 2016 README on felipesanches/trufont
* I forgot to add trufont/trufont as an upstream remote and fetch/rebase

**Pull request closed without merging**
