### PR TITLE
Refactoring the whole codebase (spliting classes to their own individual source files)

### PR DESCRIPTION
**Pull request by felipesanches**
With the purpose of reducing cruft and improving readability and maintainence.

### CODE REVIEW

**Comment by felipesanches** [comment]
@adrientetar Please leave it open until we reach that point in time after a stable release when it is appropriate for me to rebase this against master for proper merge. There's no harm in leaving it open while it is not settled.

**Comment by felipesanches** [comment]
I know this branch is currently not ready for merge due to conflicts introduced by recent code changes in master. I'll gladly take care of updating this branch once we have a stable release and the window is reopened for a new development cycle.

**Comment by adrientetar** [comment]
This PR is irrelevant now that glyphView was rewritten.

**Comment by felipesanches** [comment]
Not really... The codebase is still pretty messy. Please consider actually reading the contents of the commits in this pull request and you'll see what are the improvements I'm suggesting.

**Pull request closed without merging**
