### PR TITLE
Reworked Font Info dialog

### PR DESCRIPTION
**Pull request by madig**
First mostly-skeleton.

*Not for merging*, rather for comments. Most non-QLineEdits are dummies still and QCheckBoxes need to have their layout flipped.

There is a lot of repetition in the way the vast majority of fields in the Opentype and Postscript tab are set up, I want to do a compression pass after I get it all working.

### CODE REVIEW

**Comment by adrientetar** [comment]
> generalLayout = QHBoxLayout()

QHBoxLayout(self) & same for other layouts.

> self.nameRecordsEdit = QTableWidget()

QTableWidget(self) etc.

**Comment by madig** [comment]
Is that necessary when I add them to layouts a few lines later?

**Comment by adrientetar** [comment]
Well I do this for every widget so it alerts me when absent when reading the code.

**Comment by madig** [comment]
Doing `QHBoxLayout(self)` for sub-layouts gives me warnings like `QLayout: Attempting to add QLayout "" to GeneralTab "", which already has a layout`. So it works for the top-level layout but not for everything below it. Will try with widgets.

**Comment by adrientetar** [comment]
> Doing QHBoxLayout(self) for sub-layouts gives me warnings like QLayout: Attempting to add QLayout "" to GeneralTab "", which already has a layout.

Right. I don't do much nested layouts, my bad.

**Comment by adrientetar** [comment]
I think we can remove RLabel definition altogether given QFormLayout.

**Comment by madig** [comment]
On my todo list, it's still in use by the inspector window.

**Comment by madig** [comment]
Is there a specific reason integer/float attributes are presented as a QLineEdit?

**Comment by adrientetar** [comment]
Instead of?

**Comment by madig** [comment]
QSpinBox, QDoubleSpinBox

**Comment by adrientetar** [comment]
Isn't that what QIntValidator/QDoubleValidator are already doing? Where were you allowed to type invalid input?

**Comment by madig** [comment]
Yes, but QSpinBox does validation, probably also correct decimal mark handling per locale and gives the user arrows and up/down arrow handling :) I find it a more natural fit.

By invalid input I mean things that pass through QIntValidator/QDoubleValidator but fail validation by ufolib upon assignment.

**Comment by madig** [comment]
Found it. `openTypeHeadCreated`. Enter something bogus and you get a backtrace or a crash. Guess I'll make it a QDateTimeEdit thing.

**Comment by madig** [comment]
It just occurred to me that maybe the dialog should only save attributes that the user changed, otherwise Trufont thinks the UFO has changed just because the user opened the font info dialog and clicked Ok without changing anything. This is getting more complicated. Ugh.

**Comment by adrientetar** [comment]
Really? Normally setters in ufo3 defcon return early when given the same value. If not it should be investigated.

**Comment by adrientetar** [comment]
Oh nevermind I'm not sure it does that for font info attributes since it's dict object. I'll check tomorrow.

**Comment by madig** [comment]
Thanks. I think the dialog is almost done. Comments please :) If the code is okay, I'll take care of the unit test.

**Comment by madig** [comment]
Hm. Fields without a checkbox (General, Legal) are saved as empty strings and turn up as such in fontinfo.plist. Should those empty strings be None'd? Empty edit boxes with checkboxes should save empty strings imo, because a checkmark implies the user wanted an empty string.

**Comment by madig** [comment]
Uh wait, the code is not ready. I forgot I still have to implement the gasp and name record table thingies. Gah.

**Comment by madig** [comment]
@adrientetar in the interest of finally getting this in, how about I remove the gasp and name record tables for now and fix the unit tests, then work on the omitted tables at a later point? I'm still trying to wrap my head around the model/view thing and it will probably take some more time...

**Comment by adrientetar** [comment]
Sure.

**Comment by madig** [comment]
@adrientetar Done. Ready for comments and merging :)

**Comment by madig** [comment]
Huh. Why is the test failing.

**Comment by davelab6** [comment]
> sudo apt-get install -qq -y python3-pyqt5 python3-pip python3-flake8

I don't see why this would timeout...

**Comment by khaledhosny** [comment]
Just restart the build and see, it happened to me more than once that apt-get commands timed out on Travis, slow network or somesuch.

**Comment by madig** [comment]
If in doubt, try turning it off and on again :)

**Comment by adrientetar** [comment]
Question: why, e.g. for the General tab are there multiple QFormLayout used? It wouldn't be possible to fit the multiple areas on one form layout?

**Comment by madig** [comment]
I haven't found a way to nest or subdivide QFormLayouts, so I nested them inside box layouts instead. This sadly means that fields do not align over the entire tab in e.g. OpenType and PostScript.

**Comment by adrientetar** [comment]
Landed, thanks for this great work.

**Pull request closed without merging**
